# Generated by Django 4.1.5 on 2023-02-08 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipy', '0003_alter_recipe_description_alter_step_description'),
    ]

    operations = [
        migrations.RunSQL(
            # Deleting everything like this because CASCADE keyword is not
            # supported on sqlite and in postgres, CASCADE is not implicit.
            "DELETE FROM recipy_ingredient; "
            "DELETE FROM recipy_step; "
            "DELETE FROM recipy_recipe; ",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
