# Generated by Django 4.1.7 on 2023-02-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0008_alter_recipe_image'),
    ]

    operations = [
        # Set all image attributes to null where we find the old default recipe
        # image URL.
        migrations.RunSQL(
            "UPDATE recipy_recipe "
            "SET image=null "
            "WHERE image='defaults/recipe.jpg'; ",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
