# Generated by Django 4.1.7 on 2023-02-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipy', '0009_delete_recipe_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, choices=[('KG', 'Kilogram'), ('LITER', 'Liter'), ('TABLESPOON', 'Tablespoon'), ('TEASPOON', 'Teaspoon'), ('PIECE', 'Piece'), ('TO_TASTE', 'To taste')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
