version: '3'

volumes:
  production_postgres_data: {}
  production_traefik: {}

services:
  django:
    build:
      context: ..
      dockerfile: ./docker/production/django/Dockerfile

    depends_on:
      - postgres
    env_file:
      - ../.envs/.env  # NOTE: not part of the project, needs to be created
    image: recipy_production_django
    container_name: recipy_production_django
    command: /start

  postgres:
    build:
      context: ..
      dockerfile: ./docker/production/postgres/Dockerfile

    image: recipy_production_postgres
    container_name: recipy_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.envs/.env  # NOTE: not part of the project, needs to be created

  traefik:
    build:
      context: ..
      dockerfile: ./compose/production/traefik/Dockerfile
    image: recipy_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
